### PR TITLE
Update and rename aws-ebs-spanshot-dump.md to aws-ebs-snapshot-dump.md

### PR DESCRIPTION
**Pull request by Fumenoid**
File Renamed-

Changed Heading, as it should have been snapshot dump instead of spanshot dump.

### CODE REVIEW

**Comment by za** [comment]
Hi @carlospolop I think this is a good catch on typo. Any comment/feedback on the PR?

**Comment by carlospolop** [comment]
Hey! Thanks @Fumenoid and @za 
I need to close this PR because updating only the file nae in github will make the gitbook miss the page, so I have updated the name in gitbook but thanks for the PR!

**Comment by za** [comment]
Ah the PR also needs to update _the filename_ cc: @Fumenoid .

**Comment by Fumenoid** [comment]
All good, the main goal was for it to be corrected.. thanks for the fix @carlospolop and @za for pickin it up, Appreciate it :D

**Comment by za** [comment]
Note: issue has been fixed on this commit https://github.com/carlospolop/hacktricks-cloud/commit/25935ea6529c37073805df459131de17f9b5968f 🚀

**Pull request closed without merging**
